### ISSUE TITLE
error installing past 62 percent and cannot locate npmlog

### ISSUE THREAD

**Issue by JoshMarvel17** [wombats-writing-code/xoces#1]
the errors i'm getting

C:\Users\xoces>npm install
module.js:327
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at C:\Users\zz-jmarvel\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js:19:13
    at Object.<anonymous> (C:\Users\zz-jmarvel\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js:75:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

**Comment by luwen-huang** [comment]
Do you have this problem only with this repo or whenever you try to `npm install`? 

Is it related to this issue? http://stackoverflow.com/questions/34010476/cannot-find-module-npmlog-error-message-when-using-npm-command

**Comment by JoshMarvel17** [comment]
Sorry finally got it installed, and said the bundle was fully built.  However, what is the correct url we should put in our browser?  http://localhost:8080 does not seem to work even though the bundle says it's complete.

**Comment by luwen-huang** [comment]
could you please open a new issue so we can more specifically track bugs -- give screenshots of your terminal log (what it shows when it runs webpack), your browser log, and directory structure.
